### PR TITLE
Use production server to instantiate client

### PR DESCRIPTION
**Pull request by mroloux**

### CODE REVIEW

**Review by bverbeken — APPROVED** [review]

**Comment by csandman** [comment]
Thanks for this, this issue was driving me nuts for the past day. Any chance you all could update the module version on the go package repo? It seems like that's not being kept up to date.

**Comment by mroloux** [comment]
@schaloner any idea why seatsio-go isn't getting updated on https://pkg.go.dev/github.com/seatsio/seatsio-go?

I tried a bunch of things in our release script, but no success.

**Comment by schaloner** [comment]
Weird, that's now a bunch of releases behind even going back to when it was a manual request. I'll contact the admins and check what's happening

**Comment by csandman** [comment]
It's probably because major releases for go modules (everything > 2.0.0) are required to be segmented based on that major version. It should work if you change the module name in the `go.mod` to `module github.com/seatsio/seatsio-go/v5`.

https://go.dev/doc/modules/release-workflow#breaking
https://go.dev/doc/modules/managing-source

**Comment by schaloner** [comment]
Superb, thanks for the info. I'll sort that out later. Much appreciated!

**Pull request merged**
